version: '3.7'

services:
  flask-api:
    build:
      context: ./server/
      dockerfile: Dockerfile
    ports:
      - "9997:5000"
    env_file: ./.env
    environment: 
      DB_HOST: ${DB_HOST}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
    
    depends_on: 
      - database
    
    networks: 
      - flaskmysql
    
    volumes:
      - ./server:/app
  
  flask-web:
    build:
      context: ./web/
      dockerfile: Dockerfile
    ports:
      - "9998:5000" 
    restart: always
    env_file: ./.env
    environment: 
      DB_HOST: ${DB_HOST}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
    depends_on: 
      - database 
    
    networks: 
      - flaskmysql
    volumes:
      - ./web:/app

  database:
    image: mysql/mysql-server:8.0
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    env_file: ./.env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    volumes:
      - db-data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d
    tty: true
    networks: 
      - flaskmysql

volumes:
  db-data:

networks:
    flaskmysql:
        driver: bridge
