version: '3.7'

# Define services
services:
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9998:5000" 
    restart: always
    env_file: ./.env
    environment: 
      DB_HOST: ${DB_HOST}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
    depends_on: 
      - database # This service depends on mysql. Start that first.
    
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - flaskmysql

      # Database Service (Mysql)
  database:
    image: mysql/mysql-server:8.0
    ports:
      - "9999:3306"
    command: --default-authentication-plugin=mysql_native_password
    env_file: ./.env
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: flaskDB
      MYSQL_USER: root
      MYSQL_PASSWORD: 1234
    volumes:
      - db-data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d
    tty: true
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - flaskmysql

# Volumes
volumes:
  db-data:

 # Networks to be created to facilitate communication between containers
networks:
    flaskmysql:
        driver: bridge
